# Generated by Django 3.2.3 on 2021-05-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0002_auto_20210521_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
