# Generated by Django 3.2.3 on 2021-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publicaccessdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=20)),
                ('first_contact', models.CharField(max_length=13)),
                ('second_contact', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('facilities', models.TextField()),
                ('desc', models.TextField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
